arch: amd64

language: java

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2

env:
  - CI=true

script:
  - ./mvnw clean verify package

after_success:
  - ./mvnw clean test jacoco:report coveralls:report
